# Generated by Django 4.2.7 on 2023-12-22 03:00

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_phone_number',
            field=models.CharField(max_length=13, validators=[user.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[user.validators.validate_phone_number]),
        ),
    ]
