# Generated by Django 4.2.7 on 2023-11-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guardian_name_initial',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
