# Generated by Django 4.2.7 on 2023-11-27 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('Cluster Program Manager', 'Cluster Manager'), ('Clinical Service Officer', 'Clinical Officer'), ('Data Monitoring Documentation Officer', 'Data Monitoring Officer'), ('Deputy Director (LS)', 'Deputy Ls Director'), ('Deputy Director (SI)', 'Deputy Si Director'), ('Assistent Director (ICTC)', 'Assistant Ictc Director'), ('Assistent Director (TI)', 'Assistant Ti Director'), ('Assistent Director (IEC)', 'Assistant Iec Director')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='Experience/'),
        ),
        migrations.AlterField(
            model_name='hsc',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='HSC/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='mark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pg',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='PG/'),
        ),
        migrations.AlterField(
            model_name='preferedexperience',
            name='NOC',
            field=models.ImageField(blank=True, null=True, upload_to='NOC/'),
        ),
        migrations.AlterField(
            model_name='preferedexperience',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='PreferedExperience/'),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='SSLC/'),
        ),
        migrations.AlterField(
            model_name='ug',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='UG/'),
        ),
    ]
