# Generated by Django 4.2.7 on 2023-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_hsc_percentage_alter_pg_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='course',
            field=models.CharField(choices=[('UG', 'Ug'), ('PG', 'Pg')], default='UG', max_length=50),
        ),
    ]
