# Generated by Django 4.2.7 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_position_alter_experience_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='board',
        ),
        migrations.RemoveField(
            model_name='preferedexperience',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='ug',
            name='board',
        ),
        migrations.AlterField(
            model_name='preferedexperience',
            name='company',
            field=models.CharField(choices=[('NACO', 'Naco'), ('TANSACS', 'Tansacs'), ('TSU', 'Tsu')], max_length=100),
        ),
    ]
