# Generated by Django 4.2.7 on 2023-11-28 23:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_pg_board_remove_preferedexperience_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('c_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
