# Generated by Django 4.2.7 on 2023-12-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_experience_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pg',
        ),
        migrations.RemoveField(
            model_name='job',
            name='prefered_experience',
        ),
    ]
