# Generated by Django 4.2.7 on 2023-11-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
    ]
