# Generated by Django 4.2.7 on 2023-12-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_experience_remove_job_pg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='pg',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='preferedexperience',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pexp', to='jobs.job'),
        ),
    ]
