# Generated by Django 4.2.7 on 2023-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_id',
            field=models.CharField(default='TAN00000', max_length=50),
        ),
    ]
