# Generated by Django 4.2.7 on 2023-11-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_job_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hsc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_hsc', to='jobs.hsc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('Cluster Program Manager', 'Cluster Manager'), ('Clinical Service Officer', 'Clinical Officer'), ('Data Monitoring Documentation Officer', 'Data Monitoring Officer'), ('Deputy Director (LS)', 'Deputy Ls Director'), ('Deputy Director (SI)', 'Deputy Si Director'), ('Assistent Director (ICTC)', 'Assistant Ictc Director'), ('Assistent Director (TI)', 'Assistant Ti Director'), ('Assistent Director (IEC)', 'Assistant Iec Director')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='sslc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_sslc', to='jobs.sslc'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailOfJob_ug', to='jobs.ug'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
