# Generated by Django 4.2.7 on 2023-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_hsc_alter_job_position_alter_job_sslc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferedexperience',
            name='NOC',
        ),
        migrations.AddField(
            model_name='job',
            name='NOC',
            field=models.ImageField(blank=True, null=True, upload_to='NOC/'),
        ),
    ]
