# Generated by Django 4.2.7 on 2023-12-03 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_preferedexperience_noc_job_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pg',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ug',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
