# Generated by Django 4.2.7 on 2023-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_hsc_percentage_alter_pg_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsc',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pg',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ug',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
