# Generated by Django 4.2.7 on 2023-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
