# Generated by Django 4.2.7 on 2023-12-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_hsc_last_name_alter_pg_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='NOC',
        ),
        migrations.AddField(
            model_name='preferedexperience',
            name='NOC',
            field=models.ImageField(blank=True, null=True, upload_to='NOC/'),
        ),
    ]
