# Generated by Django 4.2.7 on 2023-12-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_noc_preferedexperience_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pg',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ug',
            name='degree',
            field=models.CharField(max_length=200),
        ),
    ]
