# Generated by Django 4.2.7 on 2023-12-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
