# Generated by Django 4.2.7 on 2023-12-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='course',
            field=models.CharField(choices=[('UG', 'Ug'), ('PG', 'Pg'), ('PHD', 'Phd')], default='UG', max_length=50),
        ),
    ]
