# Generated by Django 4.2.7 on 2023-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_experience_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslc',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
