export const CLUSTER_MANAGER = 'Cluster Programme Manager'
export const CLINICAL_OFFICER = 'Clinical Services Officer'
export const DATA_MONITORING_OFFICER = 'Data Monitoring and Documentation Officer'
export const DEPUTY_LS_DIRECTOR = 'Deputy Director (LS)'
export const DEPUTY_SI_DIRECTOR = 'Deputy Director (SI)'
export const ASSISTANT_ICTC_DIRECTOR = 'Assistant Director (BSD) /(ICTC)'
export const ASSISTANT_TI_DIRECTOR = 'Assistant Director (PREVENTION) /(TI)'
export const ASSISTANT_IEC_DIRECTOR = 'Assistant Director (IEC)'